{% set name = "google-cloud-language" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-language-{{ version }}.tar.gz
  sha256: 5f184409f040c0c73057c2616e6bd2e86e45aeb646180d19c189df4aa3d02dba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.language
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python
  summary: Google Cloud Language API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Python Client for Google Cloud Natural Language
    -------------------------

    The [Google Cloud Natural Language](https://cloud.google.com/natural-language/) API can be used to reveal the
    structure and meaning of text via powerful machine
    learning models. You can use it to extract information about
    people, places, events and much more, mentioned in text documents,
    news articles or blog posts. You can use it to understand
    sentiment about your product on social media or parse intent from
    customer conversations happening in a call center or a messaging
    app. You can analyze text uploaded in your request or integrate
    with your document storage on Google Cloud Storage.

    - [Client Library Documentation](https://googleapis.dev/python/language/latest/index.html)
    - [Product Documentation](https://cloud.google.com/language/docs)

    **note**

        This library currently does not run on Google App Engine Standard.
        We are actively working on adding this support.

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.6


  doc_url: https://googleapis.dev/python/language/latest/index.html
  dev_url: https://github.com/googleapis/python-language

extra:
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
